### ISSUE TITLE
Seeing some errors while loading data

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper-loader#104]
This appears occasionally while loading data

Streaming grasshopper-loader/scratch/244854559190571/tl_2014_16057_addrfeat/tl_2014_16057_addrfeat.shp to elasticsearch.
grasshopper-loader/grasshopper-loader.js:68
        throw err;
              ^
Error: Loaded: 29269
Present in file: 30866

    at verifyResults (grasshopper-loader/lib/verify.js:57:25)
    at grasshopper-loader/lib/verify.js:63:22
    at grasshopper-loader/grasshopper-loader.js:172:9
    at grasshopper-loader/node_modules/pump/index.js:72:4
    at f (grasshopper-loader/node_modules/pump/node_modules/once/once.js:17:25)
    at grasshopper-loader/node_modules/pump/index.js:30:3
    at f (grasshopper-loader/node_modules/pump/node_modules/once/once.js:17:25)
    at writeStream.onfinish (grasshopper-loader/node_modules/pump/node_modules/end-of-stream/index.js:30:18)
    at writeStream.emit (events.js:129:20)
    at finishMaybe (grasshopper-loader/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (grasshopper-loader/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at writeStream.Writable.end (grasshopper-loader/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at Lump.onend (grasshopper-loader/node_modules/lump-stream/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at Lump.g (events.js:199:16)
    at Lump.emit (events.js:129:20)
    at grasshopper-loader/node_modules/lump-stream/node_modules/readable-stream/lib/_stream_readable.js:934:16

**Comment by wpears** [comment]
Closed by #125
