### ISSUE TITLE
Error: stream was destroyed

### ISSUE THREAD

**Issue by hkeeler** [cfpb/grasshopper-loader#183]
The `Error: stream was destroyed` error has started popping up.  In the last couple Travis builds we've had something similar to https://travis-ci.org/cfpb/grasshopper-loader/builds/116299547#L873-L892, where tests fail due to this error.  However, it not always the same tests.

```
not ok 84 Doesn't err in a correct pipeline
  ---
    operator: notOk
    expected: |-
      false
    actual: |-
      [Error: stream was destroyed]
    at: f (/usr/src/app/node_modules/once/once.js:17:25)
  ...
ok 85 Transforms properly in retriever pipeline when file is streamed
ok 86 Passes through error when encountered in the pipeline
not ok 87 Doesn't err in a correct pipeline
  ---
    operator: notOk
    expected: |-
      false
    actual: |-
      [Error: stream was destroyed]
    at: f (/usr/src/app/node_modules/once/once.js:17:25)
  ...
```

I am seeing this same error while attempting to upload address point data (https://github.com/cfpb/grasshopper/issues/209).  Almost every file uploads, but then fails at the end with the following, and does not associate the index to the `address` alias.

```
error:  Error: stream was destroyed
    at /usr/src/app/node_modules/pump/index.js:44:21
    at call (/usr/src/app/node_modules/pump/index.js:49:3)
    at Array.forEach (native)
    at /usr/src/app/node_modules/pump/index.js:71:16
    at f (/usr/src/app/node_modules/once/once.js:17:25)
    at /usr/src/app/node_modules/pump/index.js:30:5
    at f (/usr/src/app/node_modules/once/once.js:17:25)
    at DestroyableTransform.onfinish (/usr/src/app/node_modules/end-of-stream/index.js:30:18)
    at DestroyableTransform.emit (events.js:117:20)
    at finishMaybe (/usr/src/app/node_modules/centroid-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (/usr/src/app/node_modules/centroid-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at DestroyableTransform.Writable.end (/usr/src/app/node_modules/centroid-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at DestroyableTransform.onend (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at endReadableNT (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:865:12)
info: Finished processing new_york. Total processed count: 13. Record count: 14
``` 

Also of note, I have **not** had any issue while uploading Census TIGER data.

The error itself originates from [pump](https://github.com/mafintosh/pump):
* https://github.com/mafintosh/pump/blob/6abb030191e1ccb12c5f735a4f39162307f93b90/index.js#L44

@wpears, any thoughts?  Perhaps a recent upgrade to pump has broken something?

**Comment by wpears** [comment]
This should be fixed by #184

**Comment by hkeeler** [comment]
I'll close this out once I can confirm this fixes issues I've been having while working cfpb/grasshopper#209.

**Comment by hkeeler** [comment]
Not seeing this error crop up anymore.  Closing.
